### ISSUE TITLE
LGPL + BSD/MIT dual license? :)

### ISSUE THREAD

**Issue by dormando** [dgryski/libchash#10]
Any chance of getting a more permissible license added to this? I need something almost exactly like it and it'd be nice to start from what looks like tested/used code instead of writing from scratch.

Thanks!

**Comment by ericherman** [comment]
LGPL allows the creation of a proprietary work which uses the library; only source (including changes) to the library remain LGPL. What is the license challenge you are facing?

**Comment by dormando** [comment]
For my program most consistent hashing modes are loaded as dynamic libs, which work completely fine with LGPL. However I'm also embedding two chashes into the main BSD code for no-dependency user defaults, and I'd need to change the code a bit to get there. So far as I understand that's not a compatible usage of LGPL.

It looks like chash has most of the changes I was going to do anyway, and all I'd have to modify is externalizing the hash function and some other small changes.

edit: also I don't think I could distribute with part of the code being LGPL given the rest of the project is BSD, even if that were possible to embed it.

**Comment by ericherman** [comment]
> For my program most consistent hashing modes are loaded as dynamic libs, which work completely fine with LGPL. However I'm also embedding two chashes into the main BSD code for no-dependency user defaults, and I'd need to change the code a bit to get there. So far as I understand that's not a compatible usage of LGPL.

I am not a lawyer. My thinking is that if a work uses this library and distributes the source (including the changes made), and the end users can modify and rebuild with their own additional modifications to the library, I believe that would confer the rights of the LGPL.

> It looks like chash has most of the changes I was going to do anyway, and all I'd have to modify is externalizing the hash function and some other small changes.

We could certainly expose the hashing function to the API, that is straight-forward.
 
> edit: also I don't think I could distribute with part of the code being LGPL given the rest of the project is BSD, even if that were possible to embed it.

Oh. That sounds like an organizational issue, rather than a legal or a technical issue.

**Comment by dormando** [comment]
> I am not a lawyer. My thinking is that if a work uses this library and distributes the source (including the changes made), and the end users can modify and rebuild with their own additional modifications to the library, I believe that would confer the rights of the LGPL.

IANAL either :) I'm sure that set of steps is possible, but I'm not sure if it's plausible given the wide install base of the software. Every user would have to ensure they're also providing the source for just one of the sub-source files. I can think of a lot of places which would just patch it out, which would be pretty bad for me. If I weren't intending to use it as a shipped-with feature there'd be nothing wrong with the LGPL given its linking provisions. I have a whole thing which lets BSD/LGPL/Apache code work with the main software fine, just not for the built-in algorithms.

> Oh. That sounds like an organizational issue, rather than a legal or a technical issue.

Yeah. It's both. It's just not pragmatic so far as I understand, and when dealing with licenses as the person shipping the software I'd have to understand it :) It'd be easier for me to write the thing than find a lawyer to 100% clear this up for me (and less work if community balks at it as well).

No big deal if you don't want to, I'll just write my own modified from the original ketama since that was BSD'd. Was just hoping to save some time and I trust the authors of libchash to have done it properly. Sorry for the interruption and thanks for responding so quickly!

**Comment by ericherman** [comment]
> No big deal if you don't want to, I'll just write my own modified from the original ketama since that was BSD'd. Was just hoping to save some time and I trust the authors of libchash to have done it properly. Sorry for the interruption and thanks for responding so quickly!

It's not a lot of code, even tests included.

You may also wish to check out https://arxiv.org/pdf/1406.2294v1.pdf as we switched from libchash to libjumphash for my work's usecase.

**Comment by dormando** [comment]
I'll write ten bugs into a three line codebase :) Yeah it's not bad, I just have a lot to do and was hoping to avoid some of the QA work on this.

Jump is the other default chash for the program, and has been in there a year now. Some paranoid folks and smaller outfits (just a couple of servers) still need the remove-from-any-position-and-shrink-list feature of ketama. Or for some reason they can't get the server list in the same order... Either way my two built-ins are jump and non-float non-md5 ketama. Everything else someone specialized will be modular.

Trying for a small set of sensible defaults vs just building in 50 hashing methods and confusing people.

anyway thanks! Closing this out.
