### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [dgryski/libchash#4]
I would like to point out that an identifier like "[`_CHASH_H_`](https://github.com/dgryski/libchash/blob/99c676671104bac0dea86adb6b1aead19f54d280/chash.h#L2)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by dgryski** [comment]
Please contribute to this repository with pull requests, not issues. 

If you plan on submitting many fixes, I will give you a commit bit. 

Please be aware of any changes that break API or ABI compatibility.

**Comment by elfring** [comment]
Thanks for [your improvement of an affected include guard](https://github.com/dgryski/libchash/commit/833236682a735231ccc916271b7486f4b1c55bdc "Renaming of an include guard").
