### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [dgryski/libchash#7]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/dgryski/libchash/blob/2315d5f832031a8ab391bdba528afc88e209675f/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by dgryski** [comment]
Which checks in particular?

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.3/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?

**Comment by dgryski** [comment]
```m4
# Checks for header files.                                                                                                                                                                        
AC_CHECK_HEADERS([stdint.h stdlib.h string.h])                                                                                                                                                    
                                                                                                                                                                                                  
# Checks for typedefs, structures, and compiler characteristics.                                                                                                                                  
AC_TYPE_SIZE_T                                                                                                                                                                                    
AC_TYPE_UINT32_T                                                                                                                                                                                  
                                                                                                                                                                                                  
# Checks for library functions.                                                                                                                                                                   
AC_FUNC_MALLOC
```

All these features are present on a reasonable C install.  I will not add automake support.

If you wish to do so, please file a pull request.
